# -*- coding: utf-8 -*-
"""jobtextrecover2simpletexts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/tatytapok/84138fad8a165a9695725a5d0bfd5f99/jobtextrecover2simpletexts.ipynb
"""

!pip install python-docx

#импортируем необходимые библиотеки
from docx import Document
from google.colab import files
import re

uploaded = files.upload()

def clean_links(text: str) -> str:
  """ -> str - просто для удобства и анализа восприятия кода оно показывает, что функция должна возвращать строковый тип данных """
  #links to txt

  #clin links in brackets
  text = re.sub(r'\s*\(https?://[^\s)]+\)','',text)
  """ sub(1,2,3) 1 - патерн, который нужно найти в строке для замены, 2 - то на что заменяем, 3 - где заменяем >> sub - функция для замены какого-то патерна в файле на что-то другое"""
  #clin nacked links
  text = re.sub(r'https?://[^\s]+','',text)
  return text.strip()

def format_docx(input_path: str, output_path: str):
  doc = Document(input_path)

  formatted_blocks = []
  photo_blocks = []
  list_items = []
  in_list = False

  for para in doc.paragraphs:
    text = para.text.strip()

    """Метод strip() очищает строку по краям, чтобы дальше с ней было удобнее работать.
    Что именно нужно удалить, определяет программист.
    По умолчанию удаляются все пробельные символы:
    пробел (" "), таб (\t), перевод строки (\n), возврат курсора (\r), табуляция (\v) и перевод страницы (\f). """

#Если абзац пустой он пропускается
    if not text:
      continue

    text = clean_links(text)

    #photo cheker
    if text.lower().startswith("фото"):
      photo_blocks.append(f'<p style ="font-size:12px"> {text}</p>')
      continue

    #list cheker
    if para.style.name.startswith("List"):
      list_items.append(f"<li>{text}</li>")
      in_list = True
      continue
    else:
      if in_list:
        formatted_blocks.append("<ul>\n"+ "\n".join(list_items) + "\n</ul>")
        list_items = []
        in_list = False

    #normal pharagraf
    formatted_blocks.append(f"<p>{text}</p>")

  #if doc is finished by list
  if list_items:
    formatted_blocks.append("<ul>\n"+ "\n".join(list_items)+ "\n</ul>")

  #photoblock in start
  result = photo_blocks +formatted_blocks

  with open(output_path, "w", encoding="utf-8")  as f:
    f.write("\n".join(result))

if __name__ =="__main__":
  format_docx(
      input_path="photo.docx",
      output_path="output.txt"
  )

format_docx("photo.docx", "output.txt")
files.download("output.txt")